server:
  port: 1212

spring:
  application:
    name: cloud-test-sharding


# 配置真实数据源
#dataSources:
#  # 配置第 1 个数据源
#  ds0: com.alibaba.druid.pool.DruidDataSource
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/sharding_jdbc?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
#    username: root
#    password: gosuncn

#  datasource:
#    # 当前数据源操作类型
#    type: com.alibaba.druid.pool.DruidDataSource
#    # mysql驱动类
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/sharding_jdbc?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
#    username: root
#    password: gosuncn
#    enable: true











