spring:
  application:
    name: cloud-config-center-server
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/local
#  profiles:
#    active: native
  cloud:
    config:
      server:
        git:
          search-paths: spring-cloud-samples
          uri: https://github.com/WeiSam/spring-cloud-samples.git
      label: master

server:
  port: 3344




eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
