server:
  port: 1111

spring:
  application:
    name: cloud-sample

  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fescar?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: gosuncn
    enable: true

  redis:
    database: 0
    host: 192.168.37.193
    port: 6379
    password: gosuncn
    timeout: 3000
    redisson:
      config: classpath:redisson.yml

  #对于RabbitMQ配置
  rabbitmq:
    host: 192.168.37.193
    port: 5671
    username: root
    password: gosuncn
    template:
      retry:
        enabled: false

sam:
  json:
    prefixName: test

test:
  name: sam
  age: 100


#redisson:
#  address: redis://192.168.37.193:6379
#  password: gosuncn
#  database: 5
debug: false

#打印sql，方便调试
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


stu:
  - name: jhj
    age: 18
  - name: ioio
    age: 19



