server:
  port: 1111
#  servlet:
##    context-path: /test

http:
  port: 1155

spring:
  application:
    name: cloud-sample

  datasource:
    #自定义配置,是否启用数据库连接
    enable: true
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fescar?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: gosuncn
    druid:
      ########## 配置WebStatFilter，用于采集web关联监控的数据 ##########
      web-stat-filter:
        enabled: true                   # 启动 StatFilter
        url-pattern: /*                 # 过滤所有url
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" # 排除一些不必要的url
        session-stat-enable: true       # 开启session统计功能
        session-stat-max-count: 1000    # session的最大个数,默认100
      ########## 配置StatViewServlet（监控页面），用于展示Druid的统计信息 ##########
      stat-view-servlet:
        enabled: true                   # 启用StatViewServlet
        url-pattern: /druid/*           # 访问内置监控页面的路径，内置监控页面的首页是/druid/index.html
        reset-enable: false              # 不允许清空统计数据,重新计算
        login-username: root            # 配置监控页面访问密码
        login-password: root
      ########### 启用内置过滤器（第一个 stat必须，否则监控不到SQL）##########
      filters: stat,wall,log4j2
      # 自己配置监控统计拦截的filter
      filter:
        # 开启druiddatasource的状态监控
        stat:
          enabled: true
          db-type: mysql
          # 开启慢sql监控，超过ns 就认为是慢sql，记录到日志中
          log-slow-sql: true
          slow-sql-millis: 1
        # 日志监控，使用slf4j 进行日志输出
        slf4j:
          enabled: true
          statement-log-error-enabled: true
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false
  #  shardingsphere:
#    datasource:
#      name: ds
#      ds:
#        type: com.alibaba.druid.pool.DruidDataSource
#        # mysql驱动类
#        driverClassName: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/fescar?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
#        username: root
#        password: gosuncn


  redis:
    database: 0
    host: 192.168.78.193
    port: 6375
    password: Gosuncn@2021!
    timeout: 3000
    redisson:
      config: classpath:redisson.yml

  #对于RabbitMQ配置
  rabbitmq:
    host: 192.168.78.193
    port: 5671
    username: root
    password: Gosuncn@2021!
    template:
      retry:
        enabled: false
    listener:
      simple:
        acknowledge-mode: manual
    #消息发送到交换机是否触发回调函数 none:不,correlated:回调
    publisher-confirm-type: correlated
    #是否开启交换机路由队列失败回调,路由失败才触发
    publisher-returns: true

sam:
  json:
    prefixName: test

test:
  name: sam
  age: 100


redisson:
  address: redis://192.168.78.193:6375
  password: Gosuncn@2021!
  database: 5
debug: false

#打印sql，方便调试
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: false
    local-cache-scope: statement


stu:
  - name: jhj
    age: 18
  - name: ioio
    age: 19

## 端点暴露
management:
  endpoints:
    web:
      exposure:
        ##多个也可以用逗号隔开 info,healt
        include: "*"




