server:
  port: 1111

spring:
  application:
    name: cloud-sample
  redis:
    database: 0
    host: 192.168.27.193
    port: 6379
    password: gosuncn
    timeout: 3000
    redisson:
      config: classpath:redisson.yml
sam:
  json:
    prefixName: test

test:
  name: sam
  age: 100

redisson:
  address: redis://192.168.37.193:6379
  password: gosuncn
  database: 5


