server:
  port: 9100

spring:
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123
#    url: jdbc:mysql://localhost:13306/cmt_v2?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
#    username: gosuncn
#    password: gosuncn
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: model

service:
  payment:
    name: http://cloud-nacos-provider-paymen


