package io.sam.sdk;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.Pointer;
import com.sun.jna.win32.StdCallLibrary.StdCallCallback;
import java.nio.ByteBuffer;
/**
 * JNA Wrapper for library <b>LicenseCheck</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface LinuxLicenseCheckLibrary extends Library {
	public static final String JNA_LIBRARY_NAME = "LicenseCheck";
	public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(LinuxLicenseCheckLibrary.JNA_LIBRARY_NAME);
	public static final LinuxLicenseCheckLibrary INSTANCE = (LinuxLicenseCheckLibrary)Native.loadLibrary(LinuxLicenseCheckLibrary.JNA_LIBRARY_NAME, LinuxLicenseCheckLibrary.class);
	/**
	 * <i>native declaration : linux/LicenseCheck.h</i><br>
	 * enum values
	 */
	public static interface EnumCheckResult {
		/** <i>native declaration : linux/LicenseCheck.h:28</i> */
		public static final int E_CHECK_FAIL = -1;
		/** <i>native declaration : linux/LicenseCheck.h:29</i> */
		public static final int E_CHECK_SUCCESS = 0;
		/**
		 * \u00fb\ufffd\ufffd\ufffd\u04b5\ufffd\ufffd\ufffd\u04e6License<br>
		 * <i>native declaration : linux/LicenseCheck.h:30</i>
		 */
		public static final int E_CHECK_NO_LICENSE = 1;
		/**
		 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0427\ufffd\ufffd<br>
		 * <i>native declaration : linux/LicenseCheck.h:31</i>
		 */
		public static final int E_CHECK_OUT_OF_DATE = 2;
		/**
		 * \u03f5\u0373\u02b1\ufffd\u4c7b\ufffd\ufffd\ufffd\ufffd\ufffd\u07b8\ufffd<br>
		 * <i>native declaration : linux/LicenseCheck.h:32</i>
		 */
		public static final int E_CHECK_SYSTEM_TIME_IS_MODIFIED = 3;
		/**
		 * \u05e2\ufffd\ufffd\ufffd\ufffd\u043c\ufffd\u00bc\ufffd\ufffd\u02b1\ufffd\u4c7b\u027e\ufffd\ufffd<br>
		 * <i>native declaration : linux/LicenseCheck.h:33</i>
		 */
		public static final int E_CHECK_REGISTRY_TIME_IS_DELETED = 4;
		/**
		 * \u05e2\ufffd\ufffd\ufffd\ufffd\u043c\ufffd\u00bc\ufffd\ufffd\u02b1\ufffd\u4c7b\ufffd\u07b8\ufffd<br>
		 * <i>native declaration : linux/LicenseCheck.h:34</i>
		 */
		public static final int E_CHECK_REGISTRY_TIME_IS_MODIFIED = 5;
	};
	/** <i>native declaration : linux/LicenseCheck.h</i> */
	public static final String LC_KEY_VIDEONUM = (String)"videonum";
	/** <i>native declaration : linux/LicenseCheck.h</i> */
	public static final String LC_KEY_VALIDDATE = (String)"validdate";
	/** <i>native declaration : linux/LicenseCheck.h</i> */
	public static final String LC_KEY_GENERATETIME = (String)"generateTime";
	/** <i>native declaration : linux/LicenseCheck.h</i> */
	public interface CheckEventCbFunc extends StdCallCallback {
		void apply(int eResult, Pointer pUserData);
	};
	/**
	 * szValiddateKey:\ufffd\ufffd\u0427\ufffd\u06b9\u063c\ufffd\ufffd\u02a3\ufffd\u012c\ufffd\ufffd\ufffd\ufffdvaliddate<br>
	 * Original signature : <code>EnumCheckResult GS_LC_Init(char*, char*)</code><br>
	 * <i>native declaration : linux/LicenseCheck.h:48</i><br>
	 * @deprecated use the safer methods {@link #GS_LC_Init(ByteBuffer, ByteBuffer)} and {@link #GS_LC_Init(Pointer, Pointer)} instead
	 */
	@Deprecated 
	int GS_LC_Init(Pointer szPath, Pointer szValiddateKey);
	/**
	 * szValiddateKey:\ufffd\ufffd\u0427\ufffd\u06b9\u063c\ufffd\ufffd\u02a3\ufffd\u012c\ufffd\ufffd\ufffd\ufffdvaliddate<br>
	 * Original signature : <code>EnumCheckResult GS_LC_Init(char*, char*)</code><br>
	 * <i>native declaration : linux/LicenseCheck.h:48</i>
	 */
	int GS_LC_Init(ByteBuffer szPath, ByteBuffer szValiddateKey);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u02bc\ufffd\ufffd<br>
	 * Original signature : <code>void GS_LC_Cleanup()</code><br>
	 * <i>native declaration : linux/LicenseCheck.h:51</i>
	 */
	void GS_LC_Cleanup();
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0427\u02b1\ufffd\ufffd\u0423\ufffd\ufffd\ufffd\u00bc\ufffd\ufffd\u0635\ufffd<br>
	 * Original signature : <code>void GS_LC_SetCheckEventCb(CheckEventCbFunc, void*)</code><br>
	 * <i>native declaration : linux/LicenseCheck.h:54</i>
	 */
	void GS_LC_SetCheckEventCb(CheckEventCbFunc func, Pointer pUserData);
	/**
	 * iCheckInterval:\u0423\ufffd\ufffd\ufffd\ufffd(\ufffd\ufffd\u03bb\ufffd\ufffd)<br>
	 * Original signature : <code>EnumCheckResult GS_LC_Start(int)</code><br>
	 * <i>native declaration : linux/LicenseCheck.h:58</i>
	 */
	int GS_LC_Start(int iCheckInterval);
	/**
	 * \u0363\u05b9\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0427\u02b1\ufffd\ufffd<br>
	 * Original signature : <code>void GS_LC_Stop()</code><br>
	 * <i>native declaration : linux/LicenseCheck.h:61</i>
	 */
	void GS_LC_Stop();
	/**
	 * \u0423\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>EnumCheckResult GS_LC_GetValue(const char*, char*, int)</code><br>
	 * <i>native declaration : linux/LicenseCheck.h:64</i><br>
	 * @deprecated use the safer methods {@link #GS_LC_GetValue(String, ByteBuffer, int)} and {@link #GS_LC_GetValue(Pointer, Pointer, int)} instead
	 */
	@Deprecated 
	int GS_LC_GetValue(Pointer szKey, Pointer szValBuf, int iBufLen);
	/**
	 * \u0423\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>EnumCheckResult GS_LC_GetValue(const char*, char*, int)</code><br>
	 * <i>native declaration : linux/LicenseCheck.h:64</i>
	 */
	int GS_LC_GetValue(String szKey, ByteBuffer szValBuf, int iBufLen);
}
